version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: dockerapi
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker
      - SPRING_DATASOURCE_USERNAME=docker-user
      - SPRING_DATASOURCE_PASSWORD=88888888
    links:
      - 'db:database'
  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: docker-user
      POSTGRES_PASSWORD: 88888888
      POSTGRES_DB: docker
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 6432:5432
volumes:
  db-data:
    driver: local