server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/person_docker
    username: postgres
    password: xumuk
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher