server:
  port: 8080

spring:
  sql:
    init:
      mode: ALWAYS
  application:
    name: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher